# Generated by Django 3.1.4 on 2020-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
